// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: doctors.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createDoctor = `-- name: CreateDoctor :one
INSERT INTO doctors (name, specialty, contact)
VALUES ($1, $2, $3)
RETURNING id, name, specialty, contact, created_at, updated_at
`

type CreateDoctorParams struct {
	Name      string `json:"name"`
	Specialty string `json:"specialty"`
	Contact   string `json:"contact"`
}

func (q *Queries) CreateDoctor(ctx context.Context, arg CreateDoctorParams) (Doctor, error) {
	row := q.db.QueryRow(ctx, createDoctor, arg.Name, arg.Specialty, arg.Contact)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Specialty,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoctorByID = `-- name: GetDoctorByID :one
SELECT id, name, specialty, contact, created_at, updated_at FROM doctors WHERE id = $1
`

func (q *Queries) GetDoctorByID(ctx context.Context, id uuid.UUID) (Doctor, error) {
	row := q.db.QueryRow(ctx, getDoctorByID, id)
	var i Doctor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Specialty,
		&i.Contact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
