// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: notifications.sql

package repo

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (appointment_id, type, send_at, status)
VALUES ($1, $2, $3, $4)
RETURNING id, appointment_id, type, send_at, status, attempts, last_error, created_at
`

type CreateNotificationParams struct {
	AppointmentID uuid.UUID `json:"appointment_id"`
	Type          string    `json:"type"`
	SendAt        time.Time `json:"send_at"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.AppointmentID,
		arg.Type,
		arg.SendAt,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.AppointmentID,
		&i.Type,
		&i.SendAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const listDueNotifications = `-- name: ListDueNotifications :many
SELECT id, appointment_id, type, send_at, status, attempts, last_error, created_at
FROM notifications
WHERE status = 'pending'
  AND send_at <= now()
ORDER BY send_at ASC
LIMIT 100
`

func (q *Queries) ListDueNotifications(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listDueNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.AppointmentID,
			&i.Type,
			&i.SendAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationFailed = `-- name: MarkNotificationFailed :exec
UPDATE notifications
SET status = 'failed',
    attempts = attempts + 1,
    last_error = $2
WHERE id = $1
`

type MarkNotificationFailedParams struct {
	ID        uuid.UUID `json:"id"`
	LastError string    `json:"last_error"`
}

func (q *Queries) MarkNotificationFailed(ctx context.Context, arg MarkNotificationFailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationFailed, arg.ID, arg.LastError)
	return err
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notifications
SET status = 'sent',
    attempts = attempts + 1
WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}
