// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: patients.sql

package repo

import (
	"context"

	"github.com/google/uuid"
)

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (name, phone, email, medical_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, phone, email, medical_id, created_at, updated_at
`

type CreatePatientParams struct {
	Name      string `json:"name"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
	MedicalID string `json:"medical_id"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.MedicalID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.MedicalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPatientByID = `-- name: GetPatientByID :one
SELECT id, name, phone, email, medical_id, created_at, updated_at FROM patients WHERE id = $1
`

func (q *Queries) GetPatientByID(ctx context.Context, id uuid.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.MedicalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
